const ACTIONS = {
  TASK_ADD: "TASK_ADD",
  TASK_GET_ALL: "TASK_GET_ALL",
  TASK_REQUEST_GET_ALL: "TASK_REQUEST_GET_ALL",
  TASK_UPDATE: "TASK_UPDATE",
  TASK_DELETE: "TASK_DELETE",
};

export { ACTIONS };
